--- Dockerfile	2022-09-08 16:15:28.362380321 +0800
+++ Dockerfile_Patch	2022-09-08 16:15:26.472332086 +0800
@@ -1,4 +1,4 @@
-FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
+FROM --platform=$TARGETOS/$TARGETARCH mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim AS build
 WORKDIR /source
 
 COPY src/Nadeko.Medusa/*.csproj src/Nadeko.Medusa/
@@ -19,31 +19,35 @@
     mv /app/data /app/data_init; \
     rm -Rf libopus* libsodium* opus.* runtimes/win* runtimes/osx* runtimes/linux-arm* runtimes/linux-mips*; \
     find /app -type f -exec chmod -x {} \; ;\
-    chmod +x /app/NadekoBot
+    chmod +x /app/NadekoBot; \
+    apt-get install curl --no-install-recommends; \
+    curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /app/youtube-dl
 
 # final stage/image
-FROM mcr.microsoft.com/dotnet/runtime:6.0
+FROM --platform=$TARGETOS/$TARGETARCH mcr.microsoft.com/dotnet/runtime:6.0-bullseye-slim
 WORKDIR /app
 
+COPY --from=build /app ./
+COPY docker-entrypoint.sh /usr/local/sbin
+
 RUN set -xe; \
     useradd -m nadeko; \
     apt-get update; \
-    apt-get install -y --no-install-recommends libopus0 libsodium23 libsqlite3-0 curl ffmpeg python3 python3-pip sudo; \
-    update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1; \
+    apt-get install -y --no-install-recommends libopus0 libsodium23 libsqlite3-0 ffmpeg sudo; \
+    rm -rf /var/lib/apt/lists/*; \
     echo 'Defaults>nadeko env_keep+="ASPNETCORE_* DOTNET_* NadekoBot_* shard_id total_shards TZ"' > /etc/sudoers.d/nadeko; \
-    pip3 install --no-cache-dir --upgrade youtube-dl; \
-    apt-get purge -y python3-pip; \
+    mv /app/youtube-dl /usr/local/bin/youtube-dl; \
     chmod +x /usr/local/bin/youtube-dl; \
+    chmod +x /usr/local/sbin/docker-entrypoint.sh; \
     apt-get autoremove -y; \
     apt-get autoclean -y
 
-COPY --from=build /app ./
-COPY docker-entrypoint.sh /usr/local/sbin
-
 ENV shard_id=0
 ENV total_shards=1
 ENV NadekoBot__creds=/app/data/creds.yml
 
+LABEL org.opencontainers.image.source https://github.com/xMikux/Miku-Collection
+
 VOLUME [ "/app/data" ]
 ENTRYPOINT [ "/usr/local/sbin/docker-entrypoint.sh" ]
 CMD dotnet NadekoBot.dll "$shard_id" "$total_shards"
