name: EggHAProxy_Image

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 16 * * *"

env:
  workflow_name: EggHAProxy
  workflow_image: miku-collection:EggHAProxy
  working-directory: Docker/EggHAProxy

jobs:
  BuildEggHAProxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v3

      - name: Setup multiarch
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2.1.0

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Download EggHAProxy Source Code
        run: |
          echo "Clone EggHAProxy repo..."
          git clone https://github.com/Numa-Lab/EggHAProxy EggHAProxy
        working-directory: ${{ env.working-directory }}

      - name: Build & Push (${{ env.workflow_name }})
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.working-directory }}/EggHAProxy
          file: ${{ env.working-directory }}/EggHAProxy/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/xmikux/${{ env.workflow_image }}
