name: Build NadekoBotImage
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - NadekoBotImage/Dockerfile
      - NadekoBotImage/docker-entrypoint.sh
jobs:
  push:
    name: "xmikux:nadekobotimage"
    runs-on: self-hosted
    env:
      working-directory: ./NadekoBotImage
    steps:
      - uses: actions/checkout@v2
      #- uses: docker/setup-qemu-action@v1
      - run: |
          mv Dockerfile DockerfileCopy
          mv docker-entrypoint.sh docker-entrypointCopy.sh
          curl -Lo nadeko.tar.gz https://gitlab.com/Kwoth/nadekobot/-/archive/v3/nadekobot-v3.tar.gz
          tar -xzvf nadeko.tar.gz
          mv nadekobot-v3/* .
          mv DockerfileCopy Dockerfile
          mv docker-entrypointCopy.sh docker-entrypoint.sh
          rm nadeko.tar.gz
          rm -r nadekobot-v3
        working-directory: ${{env.working-directory}}

      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./NadekoBotImage
          file: ./NadekoBotImage/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/xmikux/miku-collection:nadekobotimage
