name: Teleport_Image

on:
  workflow_dispatch:
    inputs:
      versions:
        description: "Teleport Versions"
        required: true
        default: "latest"
      images-versions:
        description: "Docker Image Versions"
        required: true
        default: "latest"
  # schedule:
  #   - cron: "0 16 * * 1"
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - Docker/Teleport/**

env:
  workflow_name: Teleport
  workflow_image: teleport
  working-directory: Docker/Teleport

jobs:
  BuildImage:
    runs-on: ubuntu-latest
    env:
      working-directory: Docker/Teleport
    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v3

      - name: Setup multiarch
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2.2.0

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build & Push (${{ env.workflow_name }})
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.working-directory }}
          file: ${{ env.working-directory }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            version=${{ github.event.inputs.versions }}
          tags: |
            ghcr.io/xmikux/${{ env.workflow_image }}:${{ github.event.inputs.images-versions }}
