# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Trivy Analysis

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 16 * * 1'

jobs:
  build:
    name: Analysis ${{ matrix.name }} Image
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
       include:
         - name: "OCI Docker Image"
           path: "DockerImage/oci/"
         - name: "nadeko"
           path: "NadekoBot/image/"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ matrix.name }}:${{ github.sha }} ${{ matrix.path }}

      - name: Run Trivy vulnerability scanner (${{ matrix.name }})
        uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
        with:
          image-ref: '${{ matrix.name }}:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
